-- liquibase formatted sql

-- changeset VTB209274:1746525055308-1
CREATE TABLE pproduct
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account           VARCHAR(255),
    balance           DOUBLE PRECISION                        NOT NULL,
    product_type      SMALLINT,
    user_id           BIGINT,
    "product-list_id" BIGINT,
    CONSTRAINT pk_pproduct PRIMARY KEY (id)
);

-- changeset VTB209274:1746525055308-2
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset VTB209274:1746525055308-3
ALTER TABLE pproduct
    ADD CONSTRAINT "FK_PPRODUCT_ON_PRODUCT-LIST" FOREIGN KEY ("product-list_id") REFERENCES users (id);

-- changeset VTB209274:1746525055308-4
ALTER TABLE pproduct
    ADD CONSTRAINT FK_PPRODUCT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

