server:
  servlet:
    context-path: "/payments-core"         # Нужно для разделения обращений к сервисам, крутящимся на одном порту
                                          # Обращение будет выглядеть так: http://localhost:8080/payments-core
  port: 8081
spring:
  application:
    name: payments-core                   # Имя приложения
  datasource:                             # Параметры подключения к БД
    url: jdbc:postgresql://localhost:5432/db_jpa2?characterEncoding=utf-8
    username: postgres
    password: 3311
    driver-class-name: org.postgresql.Driver
    hikari:                               # Пул соединений Hikari
      maximum-pool-size: 10               # max количество подключений в пуле
      connection-timeout: 20000           # Тайм-аут соединения в миллисекундах, в течение которых клиент будет ждать нового соединения из пула.
                                          # Он выдаст исключение, SQLExceptionесли в пуле нет доступных соединений.
      minimum-idle: 5                     # мmin количество бездействующих подключений, которые следует поддерживать в пуле подключений.
      idle-timeout: 900000                # max время в миллисекундах, в течение которого соединение может оставаться бездействующим в пуле, прежде чем оно будет удалено.
      max-lifetime: 1000                  # max время в миллисекундах, в течение которого соединение может оставаться в пуле, прежде чем оно будет закрыто и заменено новым.
  jpa:
    show-sql: false                        # true - выводит в консоль запросы
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none                     # none / create-drop
#  liquibase:
#    enabled: true                              # true / false
#    url: jdbc:postgresql://localhost:5432/db_jpa2
#    change-log: classpath:/db/changelog/init-changelog.xml
#    liquibase-schema: public
#    default-schema: public
#    user: postgres
#    password: 3311
integration:
  url: http://localhost:8080/payments-app/v1/product